[package]
name = "fediproto-sync-lib"
version = "0.1.0"
edition = "2021"
description = "Shared library for fediproto-sync."
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
anyhow = "1.0.95"
openssl = "0.10.68"
thiserror = "2.0.9"

[build-dependencies]
git-version = "0.3.9"
toml_edit = "0.22.22"
