[workspace]
members = ["fediproto-sync", "fediproto-sync-auth-ui", "fediproto-sync-db", "fediproto-sync-lib"]
resolver = "2"

package.authors = []
package.homepage = ""
package.repository = ""

[profile.release]
opt-level = "s"
lto = true
