[package]
name = "fediproto-sync"
version = "0.1.0"
edition = "2021"
authors.workspace = true
homepage.workspace = true
repository.workspace = true

build = "build.rs"

[dependencies]
atprotolib-rs = { path = "../atprotolib-rs", features = [
    "apicalls",
] }
bytes = "1.9.0"
chrono = { version = "0.4.39", features = ["serde"] }
diesel = { version = "2.2.6", features = [
    "chrono",
    "postgres",
    "postgres_backend",
    "r2d2",
    "returning_clauses_for_sqlite_3_35",
    "serde_json",
    "sqlite",
    "uuid",
] }
dom_query = "0.11.0"
dotenvy = "0.15.7"
fediproto-sync-auth-ui = { path = "../fediproto-sync-auth-ui" }
fediproto-sync-db = { path = "../fediproto-sync-db" }
fediproto-sync-lib = { path = "../fediproto-sync-lib" }
image = "0.25.5"
megalodon = "0.14.1"
rand = "0.8.5"
reqwest = { version = "0.12.9", features = [
    "json",
    "rustls-tls",
], default-features = false }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[build-dependencies]
git-version = "0.3.9"
toml_edit = "0.22.22"
