[package]
name = "fediproto-sync"
version = "0.1.0"
edition = "2021"
authors.workspace = true
homepage.workspace = true
repository.workspace = true

build = "build.rs"

[dependencies]
atprotolib-rs = { git = "https://github.com/Smalls1652/atprotolib-rs.git", features = [
    "apicalls",
] }
chrono = { version = "0.4.39", features = ["serde"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
reqwest = { version = "0.12.9", features = [
    "json",
    "rustls-tls",
], default-features = false }
tokio = { version = "1.42.0", features = ["full"] }
megalodon = "0.14.1"
dotenvy = "0.15.7"
dom_query = "0.11.0"
tendril = "0.4.3"
diesel = { version = "2.2.6", features = [
    "chrono",
    "serde_json",
    "uuid",
    "postgres",
    "postgres_backend",
    "sqlite",
    "returning_clauses_for_sqlite_3_35"
] }
tokio-util = { version = "0.7.12", features = ["rt", "time"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
diesel_migrations = { version = "2.2.0", features = ["sqlite"] }
rand = "0.8.5"
uuid = { version = "1.11.0", features = ["v4", "v7", "fast-rng"] }
oauth2 = "4.4.2"
url = "2.5.4"
openssl = "0.10.68"
bytes = "1.9.0"

[build-dependencies]
git-version = "0.3.9"
toml_edit = "0.22.22"
