name: Git Town

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches-ignore: 
      - 'dependabot/**'

jobs:
  git-town:
    name: Display the branch stack
    runs-on: ubuntu-latest

    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: git-town/action@v1
